import Head from 'next/head';
import Cosmic from 'cosmicjs';
import { GetStaticProps } from 'next';

const cosmic = Cosmic();

const bucket = cosmic.bucket({
    slug: process.env.NEXT_PUBLIC_BUCKET_SLUG,
    read_key: process.env.NEXT_PUBLIC_BUCKET_READ_KEY,
});

export default function Home({ projects, features }) {
    return (
        <div>
            <Head>
                <title>Jacob Bruce</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
                <meta name='description' content="Jacob Bruce's Software Development Portfolio" />
                <meta name='keywords' content='Jacob, Bruce, Portfolio, Software Development' />
            </Head>

            <h1>Jacob Bruce</h1>
        </div>
    );
}

export const getStaticProps: GetStaticProps = async (context) => {
    const projectData = await bucket.getObjects({
        query: {
            type: 'projects',
        },
        props: 'slug,title,content,url',
    });
    const projects = await projectData.objects;
    const featuresData = await bucket.getObjects({
        query: {
            type: 'features',
        },
        props: 'slug,title,content,url,thumbnail',
    });
    const features = await featuresData.objects;
    return {
        props: {
            projects,
            features,
        },
    };
};
