import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Jacob Bruce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Jacob Bruce's Software Development Portfolio" />
        <meta name="keywords" content="Jacob, Bruce, Portfolio, Software Development" />
      </Head>

      <h1>Jacob Bruce</h1>

    </div>
  )
}
